### ISSUE TITLE
Chrome header modification after redirect doesn't work anymore

### ISSUE THREAD

**Issue by saylasr** [requestly/requestly-issues#10]
Previously it was possible to create two rules:
1) Redirect Request from one url to another
2) Add Access-Control-Allow-Origin response header for certain host, so the request is not blocked by CORS.

But in the past few days the second rule is not working. So after redirect I get the error:
XMLHttpRequest cannot load <url1>. Redirect from '<url1>' to '<url2>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '<host>' is therefore not allowed access.

**Comment by sachinjain024** [comment]
@saylasr Nothing changed inside Requestly code which can cause this issue. Can you please share your rules so that I can look into it further? If you have privacy concerns w.r.t your rules you can also send them to me on requestly.extension@gmail.com

**Comment by sachinjain024** [comment]
Closing this issue due to lack of response.
