### ISSUE TITLE
Regex is invaild.

### ISSUE THREAD

**Issue by Cologler** [requestly/requestly-issues#11]
e.g:

``` regex
http://push.gd165.com:8080/\?(?:.*)&surl=http://(.*)
```

It is a vaild regex.

**Comment by Cologler** [comment]
Also, url should allow not start with (http|https|ftp).

**Comment by sachinjain024** [comment]
@Cologler Actually, Requestly accepts a valid regex to be of this form `/someRegex/ig`. For your url, it would be

    /http:\/\/push\.gd165\.com:8080\/\?(?:.*)&surl=http:\/\/(.*)/ig

However, an easy way would be to use `Matches Wildcard` operator and you can simple use the following

    http://push.gd165.com:8080/?*&surl=http://*

Here, you will get the * values as $1, $2 respectively. Check this out: http://www.requestly.in/content/documentation/rule-operators/#wildcard-match-operator

**Comment by Cologler** [comment]
Thanks.

But how about the second idea? I want replace some url to magnet link or just use google search.

**Comment by sachinjain024** [comment]
Oh! In those cases I think you would have to go with first option. It is good to know about the second option though.

**Comment by Cologler** [comment]
(⊙﹏⊙), what do "first option" mean?

**Comment by sachinjain024** [comment]
@Cologler First option is about using Regex match and second option was about using wildcard match :-)

**Comment by sachinjain024** [comment]
@Cologler Regarding your question about:

> Also, url should allow not start with (http|https|ftp).

If you are talking about destination url, We do need to have strict comparison for destinationUrl otherwise we would not know which protocol to be used.

If you are talking about source url, you can simply use your pattern in regex match. For example check this example:

https://medium.com/@requestly_ext/create-url-shortcuts-for-jira-projects-4fd49abdcae7

**Comment by Cologler** [comment]
Is possible let this extensions work with redirect request (status code: 301, 302 and 307)?
My network provider inject AD by redirect the request. (ㄒoㄒ)

**Comment by sachinjain024** [comment]
@Cologler I dont completely follow you by this statement. Can you please help with an example ?

**Comment by Cologler** [comment]
e.g:

I was input `http://www.huya.com/`, but my network provider was response:

302 redirect to `http://push.gd165.com:8080/\?Id=????????&surl=http://www.huya.com/`

In this case, requestly was not match `http://push.gd165.com:8080/\?Id=????????&surl=http://www.huya.com/` and redirect back to `http://www.huya.com/`.

**Comment by sachinjain024** [comment]
@Cologler Where do you want to redirect this request to ? Can you show me how you are setting up your rule.

In this case, I think you should be good to follow this

RuleType: RedirectRule
Source: Url Matches (Wildcard) http://push.gd165.com:8080/\?Id=*&surl=*
Destination: http://www.someUrl.com?param1=$1 (Just an example)

There is one more thing to figure out. I am not fully sure if chrome allows you to redirect on the response of 302 location but you can test that with a simple redirect rule as well.

**Comment by Cologler** [comment]
https://developer.chrome.com/extensions/webRequest say:

> Fires when a redirect is about to be executed. A redirection can be triggered by an HTTP response code or by an extension. This event is informational and handled asynchronously. It does not allow you to modify or cancel the request.

Seem chrome does not allow we modify the request.

**Comment by Cologler** [comment]
Is any way to log whether the redirect is executed?

**Comment by sachinjain024** [comment]
@Cologler You can setup a simple Redirect Rule

Url contains push.gd
Redirect Url: https://www.facebook.com

So when your server sends 302 with push.gd in the url, this rule will try to modify and redirect it again to facebook.

If the rule works then this means your request can be intercepted otherwise not.

**Comment by Cologler** [comment]
Seem the rule:

Url equals `https://github.com/`
Redirect Url: `https://www.facebook.com`
Input `http://github.com` (not https)

It worked. 
Now I am trying to find error in my exists rule.

Thanks for your times.
