### ISSUE TITLE
Doesn't work well in mixed HTTPS/HTTP scenarios

### ISSUE THREAD

**Issue by tomprogers** [requestly/requestly-issues#12]
The site I'm debugging is fetched over HTTPS. The localhost server that provides replacement assets only supports HTTP.

The latest Chrome (v59) refuses to download replacement javascript because the host page is secure and the javascript URL is insecure. There doesn't seem to be a good way to work around this on a Mac (there is apparently a hack that works on Windows by disabling _all_ Chrome security, but that's a pretty onerous workaround, and in either case it doesn't work on a Mac).

Is there a way for your extension to work around that somehow?

**Comment by sachinjain024** [comment]
@tomprogers You are correct. Modern browsers do not allow you to load unsecure (http based) active content (scripts, stylesheets, objects etc) on secure (https) sites. This is called mixed content issue.  If there is a particular script you are trying to load into your secure site from localhost, you can use [Requestly Library](http://www.requestly.in/content/documentation/introducing-library-service/) using which you can host your localhost version on Google drive based link. 

Once you host your file on Library use the url from library in Redirect rule or Replace rule and debug your code from library.

Let me know if you have more questions.

**Comment by sachinjain024** [comment]
Closing this due to lack of response.
