### ISSUE TITLE
connect firebaseio.com?

### ISSUE THREAD

**Issue by Cologler** [requestly/requestly-issues#17]
Why does the extension connect firebaseio.com?

**Comment by sachinjain024** [comment]
@Cologler We have implemented sharedList feature and file library. We use firebase as backend for storing user's files and sharedList. You can read more about file library in this article:

https://www.requestly.in/content/documentation/introducing-library-service/

Earlier, we were storing google drive for storing user's files but now we are using firebase. 

@requestly/requestly-library We should update this document to correct implementation.

Let me know if you have other questions.

**Comment by sachinjain024** [comment]
Article about sharedLists https://www.requestly.in/content/documentation/introducing-shared-list/

**Comment by Cologler** [comment]
@sachinjain024 

But why does it connect even I did not use any feature of sharedList ?

(My 'Shared List' and 'file library' was not login).

**Comment by sachinjain024** [comment]
@Cologler Yes this is a good question. Actually we have initialized firebase in app initialisation so it just makes a connection and does not do anything. Otherwise when you create a sharedList and then we make a connection it will be a poor user experience.

**Comment by sachinjain024** [comment]
@Cologler Just asking if it is a bothering thing for you ?

**Comment by Cologler** [comment]
I just a little confused, is this extensions recording my browser history ...

![picpick-20170913-132038-001](https://user-images.githubusercontent.com/10906962/30360854-6ae94fea-9886-11e7-971c-e2e6d4f01ad7.png)

**Comment by sachinjain024** [comment]
@Cologler No! You can safely use Requestly. Here is the list of permissions required by Requestly:
https://medium.com/@requestly_ext/list-of-permissions-used-in-requestly-48a011dee133

Just in case you wanted to have a look at it too.

**Comment by Cologler** [comment]
@sachinjain024 Even requestly cannot read history, all requests will be handle by requestly since I installed it.
