### ISSUE TITLE
Change two parts to one url

### ISSUE THREAD

**Issue by usproptrader** [requestly/requestly-issues#2]
So here it is. 
Convert from

https://ca.finance.yahoo.com/q/ks?s=IBM/key-statistics?ltr=1
To

http://www.google.com/finance?q=IBM
have one key rule with 2 replacements
1st works ok
2nd to change
 /key-statistics?ltr=1"
To blank doesn't
So I get
 http://www.google.com/finance?q=IBM/key-statistics?ltr=1

**Comment by sachinjain024** [comment]
How about using this rule:

<img width="1144" alt="screenshot 2017-01-15 12 03 59" src="https://cloud.githubusercontent.com/assets/3108399/21960745/becc1cde-db1a-11e6-9036-7272ffed5299.png">

I have created a sharedList here with above rule: http://requestly.in/rules/#sharedList/1484462502829

Please open this link and click on ImportList and you should get the rule. If this does not work for you, you can type in your rule from the screenshot.

Let me know if this works for you. Thanks!!

**Comment by sachinjain024** [comment]
One more thing, Can I have a look at your rule so that I can look into this bug ? Please paste screenshot of your rule here.

**Comment by usproptrader** [comment]
Here it is


Regards
Malcolm Newton

**Comment by sachinjain024** [comment]
@usproptrader Did the above change work for you ? And I cannot see any screenshot in your comment. Can you please paste it again ?

**Comment by usproptrader** [comment]
will try tomorrow
![url](https://cloud.githubusercontent.com/assets/7141475/21998747/b3a7b026-dc04-11e6-9945-c54172678781.jpg)

**Comment by usproptrader** [comment]
The app is sending this url
http://ca.finance.yahoo.com/q/ks?s=IBM
Chrome is redirecting to
https://ca.finance.yahoo.com/quote/IBM/key-statistics?ltr=1

I need it to be 
https://www.google.com/finance?q=IBM

the new setup doesnt work probably because Chrome is redirecting

**Comment by sachinjain024** [comment]
@usproptrader When I created a rule with the above definition and then I opened 
> https://ca.finance.yahoo.com/quote/IBM/key-statistics?ltr=1

directly in the browser. It took me directly yo google finance IMB page. This is working as expected.

Which app you are using ?

**Comment by usproptrader** [comment]
Sachin
Now it works great!
Did Not have match on wildcard option selected before thanks

regards
Malcolm Newton

**Comment by sachinjain024** [comment]
Thanks @usproptrader for confirmation. Closing this ticket.
