### ISSUE TITLE
How to remove header: referer?

### ISSUE THREAD

**Issue by bestpika** [requestly/requestly-issues#20]
I want to remove referer from `foo.com`'s request.
But this rule not work.
![image](https://user-images.githubusercontent.com/5698157/33995891-57794cd0-e11a-11e7-9497-514fadff17bc.png)

**Comment by sachinjain024** [comment]
@bestpika Rule looks fine and I just tried it. It works fine for me. Is your rule active ?

Check these screenshots:

## Rule
<img width="1320" alt="screenshot 2017-12-14 20 25 18" src="https://user-images.githubusercontent.com/3108399/33998247-001ac386-e10d-11e7-9648-cd1246c617c9.png">

## Without Rule

<img width="1621" alt="screenshot 2017-12-14 20 23 12" src="https://user-images.githubusercontent.com/3108399/33998273-10df9e4e-e10d-11e7-940b-6ce0cdbe9649.png">

> You can see there is a Referer header.

## After Creating rule

<img width="1613" alt="screenshot 2017-12-14 20 24 52" src="https://user-images.githubusercontent.com/3108399/33998315-2aeec044-e10d-11e7-8ccd-3dbd6bec8cf1.png">

> You can see there is no Referer header this time.

Can you download the rule by selecting it and clicking on download button and attach the rule here ?

**Comment by sachinjain024** [comment]
You may also want to read this thread - https://medium.com/@requestly_ext/list-of-headers-not-allowed-to-be-modified-by-chrome-extensions-c850b5c02fff

**Comment by bestpika** [comment]
Well, my target site is not `foo.com` (just show my setting)
A b site's image on a site.
I try to remove a site's Referer, but not work.

![image](https://user-images.githubusercontent.com/5698157/34001803-f0716470-e12b-11e7-9c29-305e10c1f563.png)
![image](https://user-images.githubusercontent.com/5698157/34001823-fc452f52-e12b-11e7-9da9-d7d62af1bfe5.png)

**Comment by sachinjain024** [comment]
@bestpika Well, Your Source matching is wrong here. Here is the meaning of header modification rule -

> Remove Request header - Referer when the url contains foo.com

In this case, request url is the url of the request and not the referer So your rule should look something like this:

    Remove RequestHeader Referer
    Source Url Contains images.gamme.com

Notice, the request url here is for images.gamme.com and not plurk.com. Plurk.com is the referer.
You can leave this field empty too to remove Referer header from all requests.

Let me know if it helps!

**Comment by bestpika** [comment]
Ok, this extensions can't modify third-party site's referer.
(But some extension can.)

So...this could be feature request?

**Comment by sachinjain024** [comment]
@bestpika This can modify third-party site's referer. Try this:

    Remove Request Header - Referer
    Source Url Contains 

Yes leave that field empty and now try this.

**Comment by bestpika** [comment]
But I don't want to remove all site's referer...orz

**Comment by sachinjain024** [comment]
Yes! Currently we don't allow putting conditions on header values that remove header when header value contains something.

Its less likely to be supported. Reason being its not a popular request. But we may consider it in future depending upon the request popularity.

Thanks for your patience.

**Comment by sachinjain024** [comment]
Closing this ticket. @bestpika Feel free to reopen if you want to add anything here
