### ISSUE TITLE
[FR] exec user scripts in webRequest event like onBeforeRequest.

### ISSUE THREAD

**Issue by Cologler** [requestly/requestly-issues#26]
As the title says.

**Comment by sachinjain024** [comment]
@Cologler That is almost impossible to achieve. Execution of user scripts can be happen only when DOM has started loading. Chrome gives us a feature called inject content script at document_start and we inject the script that way but when we create script tag and inject it, it is executed asynchronously.

Can you explain your case ? Maybe that way I could come up with a better use case.

**Comment by Cologler** [comment]
Case 1, encodeURIComponent to use some anonymous proxy:

redirect `URL` to `http://???/?url=encodeURIComponent(URL)`

Case 2, decodeURIComponent to avoid some redirect:

redirect `http://???/?url=encodeURIComponent(URL)` to `URL`.

---

I think this is easy to achieve like:

``` js
chrome.webRequest.onBeforeRequest.addListener(() => {
    for (const scriptString in userScripts) {
        const result = eval(scriptString);
        if (result) {
            return result;
        }
    }
}
```

**Comment by sachinjain024** [comment]
@Cologler Now, I understand what you are asking. I misunderstood you first time. Infact this is in roadmap. 

Thanks for submitting this feature request. We will support this in near future. Watch this ticket for more updates.

**Comment by sachinjain024** [comment]
@Cologler It's been a long time on this ticket and I am glad to share that this feature has been rolled into production. You can encode, decode url or parts of url using Requestly's inbuilt function feature.

You can create your rule like this

Source Url Matches WildCard https://www.example.com?a=*
Destination rq_decode($1)

`rq_encode` and `rq_decode` are inbuilt functions which you can use in any of the rules. Let me know if it helps your use case.

**Comment by Cologler** [comment]
@sachinjain024 already test now. work perfect !
