### ISSUE TITLE
adding the prefix in the rule twice instead of only once

### ISSUE THREAD

**Issue by alpsinan** [requestly/requestly-issues#28]
wikipedia.com is blocked by Turkey. There is 0wikipedia.com (which is not blocked)  so i thought your app could be a solution for this. (Actually it can be a solution for many websites blocked by many governments)
. So I made a rule, wikipedia to 0wikipedia but your app makes it 00wikipedia and obviously DOS.

**Comment by sachinjain024** [comment]
@alpsinan Thanks for logging the issue. Can you tell me how your rule looks like ? Once I have rule, probably I can provide a solution to this problem.

On first look - this looks straight forward to fix this but I need your rule to look at it. If there is a bug in the code, I will let the team know it and get it fixed.

**Comment by alpsinan** [comment]
On Friday, February 9, 2018, 6:47:36 PM GMT+3, Sachin Jain <notifications@github.com> wrote:  
 
 
@alpsinan Thanks for logging the issue. Can you tell me how your rule looks like ? Once I have rule, probably I can provide a solution to this problem.

On first look - this looks straight forward to fix this but I need your rule to look at it. If there is a bug in the code, I will let the team know it and get it fixed.

**Comment by sachinjain024** [comment]
@alpsinan Can you provide the rule - A screenshot should suffice or you can share the rule using[ Requestly's sharedList feature](https://www.requestly.in/content/documentation/introducing-shared-list/).

**Comment by sachinjain024** [comment]
Closing this due to lack of inactivity.
