### ISSUE TITLE
Math operation on part of url

### ISSUE THREAD

**Issue by cibinjoseph** [requestly/requestly-issues#29]
Is there any way to do a math operation on a part of a url? 
For eg. if I wanted to increment the page number in a url like 
`http://www.book.com/book1&page=101`
to
`http://www.book.com/book1&page=102`

**Comment by sachinjain024** [comment]
Currently, there is only one function supported i.e. Random number function and users can use it like this.

    http://www.book.com/book1&page=<rq_rand(2)>

It will generate 2 digit random number every time the request is matched. Currently, there is no increment method supported but we plan to add more similar methods in future like encodeURIComponent and all. 

How urgent it is your use case ?

**Comment by cibinjoseph** [comment]
No urgency! Was looking for an extension that had capabilities like that and came across yours.

**Comment by sachinjain024** [comment]
Does random number method solve your use case ? If we give you increment, decrement operations within couple of weeks, will that be fine ?

**Comment by cibinjoseph** [comment]
Hey, please take your time on it. It was only a suggestion I thought would be a great addition! None of the extensions online have anything similar that can increment pages by modifying the url directly.
And I don't think random number method would solve it, especially for books and things like that where you'd require an explicit increment or decrement.

**Comment by sachinjain024** [comment]
Hey, @cibinjoseph I forgot to update on this ticket, we had added the support for incrementing and decrementing a part of URL. You can use Replace Rule to replace the existing param value with an incremented value something like this

## Replace Rule

**Replace**:  ?yourparam=(.+)&
**With**: rq_increment($1, 1)

**Comment by cibinjoseph** [comment]
Oh that's great! That would be helpful
