### ISSUE TITLE
Only one of N rules matching the same URL is applied

### ISSUE THREAD

**Issue by t2gran** [requestly/requestly-issues#30]
When defining several rules matching the same URL only one is applied.

Might be related to #27 

**Use Case**
I have an endpoint with more than 30 URL parameters which I want to test with different combinations of parameters. To do so I have put each parameter in its own rule (matching the same endpoint). I have done this to be able to turn each parameter on/off independently. I know I could put all parameters in the "Modifications" section under one rule, but I need to document each parameter with default value, unit and a small description to remember what they do, and -- most importantly -- be able to mix and match parameters. I never run the request with more than 10 out of 30 parameters.   

But, when I apply more than one rule, only one is added to the request.

**Solutions**
1. The best solution would be to be able to turn a parameter in a Rule on and off, and add the possibility to add some description for each parameter. 
2. Apply all matching rules 

**URL**: http://otpdebug.entur.org/otp/routers/default/plan?fromPlace=Rosenholm++(RB%3ANSR%3AStopPlace%3A62)%3A%3A59.823626%2C10.796493&toPlace=Oppsal++(RB%3ANSR%3AStopPlace%3A5994)%3A%3A59.892835%2C10.84016&time=10%3A47am&date=02-22-2018&mode=TRANSIT%2CWALK&maxWalkDistance=2000&arriveBy=false&wheelchair=false&locale=en&numItineraries=6

**Rules**

    [{
      "creationDate": 1519131750007,
      "description": "Maximum time of pre-transit travel when using drive-to-transit (park and ride or kiss and ride). Unlimited on large graphs the search becomes very slow.",
      "id": "QueryParam_223344550004",
      "name": "/plan maxPreTransitTime 1800 (INFINITE) seconds",
      "pairs": [{
        "modifications": [{
          "actionWhenParamExists": "Overwrite",
          "param": "maxPreTransitTime",
          "type": "Add",
          "value": "1800"
        } ],
        "source": {
          "key": "Url",
          "operator": "Contains",
          "value": "otp/routers/default/plan"
        }
      } ],
      "ruleType": "QueryParam",
      "status": "Inctive"
    },
    {
      "creationDate": 1519131750007,
      "description": "Max walk/bike speed along streets.",
      "id": "QueryParam_223344550005",
      "name": "/plan walkSpeed 2.0 (1.3) m/s",
      "pairs": [ {
        "modifications": [ {
          "actionWhenParamExists": "Overwrite",
          "param": "walkSpeed",
          "type": "Add",
          "value": "2.0"
        } ],
        "source": {
          "key": "Url",
          "operator": "Contains",
          "value": "otp/routers/default/plan"
        }
      } ],
      "ruleType": "QueryParam",
      "status": "Inctive"
    }]

**Comment by sachinjain024** [comment]
@t2gran We have made required changes in the code to fix the issue. We will be releasing the extension with new build soon.

**Comment by sachinjain024** [comment]
@t2gran Sorry for delayed response. This issue has been fixed and released in the latest version of chrome store about a week ago. Please try it and let us know if it solves your use case.

**Comment by sachinjain024** [comment]
@t2gran I assume the fix worked for you. Let me know if it didn't. Closing this issue for now.
