### ISSUE TITLE
Query keeps adding %3D to the end

### ISSUE THREAD

**Issue by Ryusuta** [requestly/requestly-issues#31]
Hi there. I'm attempting to use requestly to add "&disable_polymer=true" to the end of any HTML containing "watch?v=" (minus the quotes on both, of course). This is because Youtube removed the "Restore Classic Youtube button" and the only way to look at non-ugly Youtube is to add "&disable_polymer=true" to the end of all HTMLs with it. This solution ALMOST works, but I could use help figuring out this last piece of the puzzle.

What I did:

-Made a new "Modify Query Parameters" rule
-Request URL contains "watch?v="
-Add Param "&disable_polymer=true" Value [blank]

The result is that it DOES add the "&disable_polymer=true" to it, but for some reason it ALSO adds %3D, which negates the other suffix unless I manually remove it. I would really appreciate learning where I went wrong on this. Thank you!

**Comment by sachinjain024** [comment]
@Ryusuta Try modifying your rule like this

Request URL contains "watch?v="
Add Param `disable_polymer` Value `true`

<img width="1314" alt="screenshot 2018-03-17 12 33 46" src="https://user-images.githubusercontent.com/3108399/37552642-7aa2059a-29df-11e8-94bb-e2110f35ab24.png">

**Comment by Ryusuta** [comment]
I gave that a shot as well, but that changed the url to disable_polymer=**+**true

For some reason it added a plus sign to it.

**Comment by sachinjain024** [comment]
Somehow this is working perfectly fine for me. Have a look at this screenshot

<img width="1045" alt="screenshot 2018-03-17 13 09 22" src="https://user-images.githubusercontent.com/3108399/37552943-760094de-29e4-11e8-8c1b-68a278c094cb.png">

**Comment by Ryusuta** [comment]
OH! My mistake. I accidentally added a space before true. Thanks so much!
