### ISSUE TITLE
Redirect request not working

### ISSUE THREAD

**Issue by kdwk** [requestly/requestly-issues#34]
I am trying to redirect https://www.google.com to https://vqmvr8fijoybhhtmewjyxw-on.drv.tw/temporary/Google%20substitution/Google.html, which is just my modified version of the google webpage. However, as I used the 'equal' rule it appears not to work. I tried it on more popular websites like https://www.duckduckgo.com and then it works again. Is it just my problem? I am using Request 5.3.0 on Google Chrome 67.0.3396.30. Answers are appreciated and solutions are much welcome. Thank you!

**Comment by sachinjain024** [comment]
@kdwk There is a catch in using "Equals" operator. You have to append "/" at the end in this case.

Try doing this
    Source - Url "Equals" "https://www.google.com/"
    Destination - <some_other_url>

Let me know if it solves your problem.

**Comment by sachinjain024** [comment]
I just tried this rule and it worked perfectly for me

<img width="1309" alt="screenshot 2018-05-14 21 31 29" src="https://user-images.githubusercontent.com/3108399/40008939-391ad068-57be-11e8-94c0-cb7e3159e308.png">

**Comment by kdwk** [comment]
Wow thank you very much!

Sent to you by Kdwk

**Comment by sachinjain024** [comment]
@kdwk Awesome! Glad to know it worked for you. Can we close this ticket now ?

**Comment by kdwk** [comment]
Yes thank you once again!
