### ISSUE TITLE
Cannot modify Response Header

### ISSUE THREAD

**Issue by joshuabradley012** [requestly/requestly-issues#37]
Trying to modify the response header, in particular by removing `X-XSS-Protection` but it is not modifying the header. However, it does modify the request header easily.

**Comment by sachinjain024** [comment]
Hi @joshuabradley012 Thanks for opening the issue. Actually the response header gets removed but the modifications are not visible in chrome dev tools. This isa chrome bug.

Please have a look at this article - https://medium.com/@requestly_ext/list-of-headers-not-allowed-to-be-modified-by-chrome-extensions-c850b5c02fff

> Headers rule containing response header modifications actually works but the modifications are not visible in developer tools. However, modifications in request headers are visible in developer tools.

Reason for this is chrome doesn’t want to wait for extensions to finish their modifications before showing them in dev tools. Implementation of developer tools is such that they receive headers as soon as response is received and extensions are given the headers for modifications. So behind the scenes, modification is applied as long as your rule is fine but you may not know it. We understand this is hard to debug but it is an open problem.

Here is the [Chromium Bug/Pending feature](https://bugs.chromium.org/p/chromium/issues/detail?id=258064) in which this point was raised and probably this has not prioritised yet.

**Comment by joshuabradley012** [comment]
Thank you for the info!

**Comment by sachinjain024** [comment]
@joshuabradley012 Did you confirm if the removal of header is working for you or not ? Extension works perfectly but list of headers is not updated in devtools. So you can still use the extension to remove the header.
