### ISSUE TITLE
Memory leak...

### ISSUE THREAD

**Issue by isiahmeadows** [requestly/requestly-issues#4]
I noticed that this extension in Chrome, when left running in the background, slowly takes more and more memory, even when not blocking anything, and even when it's disabled. I'm pretty sure there's a memory leak in the code somewhere, considering in the span of a couple hours, it can leak as much as 70MB of memory.

**Comment by isiahmeadows** [comment]
For such a simple tool conceptually, that's way too much memory.

**Comment by sachinjain024** [comment]
@isiahmeadows Thanks for logging this. I'd definitely keep this in mind in my development and will often check for memory consumption by this.

How did you check the memory consumption? Did you use Chrome Task Manager? Here is a screenshot of my device.

<img width="893" alt="screenshot 2017-03-09 10 18 34" src="https://cloud.githubusercontent.com/assets/3108399/23736366/c9b1b274-04b1-11e7-93ec-350b367fb7b3.png">

Of all the extensions I use, Requestly came at the bottom with ~40 MBs of memory and I think that's fair. Although I can not provide the breakdown of memory consumption within the extension. The only things Requestly caches are:

1. List of all rules are in memory
2. Listeners on Storage and other chrome events

What's your expectation? What should be the memory consumption?

**Comment by isiahmeadows** [comment]
I did use Chrome's task manager. I didn't take a screenshot, though. It also takes several hours to get truly problematic (after ~10 hours, it usually hits about 300-400MB), so it's not something that quickly appears.

I would normally expect Requestly to stay near the bottom while not filtering anything, and slow memory leaks aren't easily caught.

Any idea where I could find the relevant source code? I'm actually willing to help rectify this when I can find time.

**Comment by sarathnair** [comment]
I have also experienced memory leak in program. I have set up some rules in requestly. These rules basically replace the URL. Every time I refresh my page I can see in Chrome's task manager that memory goes up and never comes down. For my application the requestly extension consumes additional 2MB memory in each page reload. This is a critical issue and should be looked into immediately.

**Comment by sachinjain024** [comment]
@sarathnair Can you please give me a screenshot of your chrome task manager. I just wanted to view the memory consumption by other tabs/processes as well before considering this as issue. Normally, chrome keeps on hogging memory if you do not refresh the page for a long time. I think the same holds true for extensions as well. Can you check the memory usage by other extensions as well ?

**Comment by sarathnair** [comment]
@sachinjain024 
![image](https://cloud.githubusercontent.com/assets/7995999/24655990/362e566c-195e-11e7-9633-3cf8301824b5.png)

Here is the screen shot you asked. After a couple of refresh I see below:

![image](https://cloud.githubusercontent.com/assets/7995999/24656105/abf02a4c-195e-11e7-81fc-0a65d58ec88f.png)

I see similar behavior in Adblocker extension. But after a while Adblocker seems to release memory and come back its previous state.

**Comment by sachinjain024** [comment]
@sarathnair @isiahmeadows Sorry for responding so late on this ticket. I actually forgot to update this one. We have made some cleanups in the code and removed some unused code+library.

I am expecting that should fix the issue. If by chance, you guys are still using Requestly (That would be a huge thing for me), can you please let me know if you face this?

**Comment by isiahmeadows** [comment]
@sachinjain024 I'm not seeing it on my end any more and haven't for a while, so I think this could be closed.

**Comment by sachinjain024** [comment]
Thanks @isiahmeadows for confirming. Feel free to give us suggestions/feedbacks.You can also reachout to us at requestly dot extension at gmail dot com.
