### ISSUE TITLE
Requestly Modify header does not remove duplicate entries

### ISSUE THREAD

**Issue by harrysingh** [requestly/requestly-issues#5]
Some of the websites send smae header twice or with difference case.
We may handle such cases

Url: www3-ist-wcp.keurig.com

**Comment by mrj** [comment]
Yes, I'm using Requestly on a website that sets the `content-security-policy` header to `upgrade-insecure-requests;, upgrade-insecure-requests;, upgrade-insecure-requests;`, which Chrome seems to expand to three separate `content-security-policy` headers. A remove rule in Requestly seems to only get rid of one of these. But I can get it to work by adding multiple identical remove rules that each get rid of one header.

**Comment by sachinjain024** [comment]
Thanks @mrj for mentioning here. We will fix this soon. Glad to know that you are already aware about the workaround.

**Comment by sachinjain024** [comment]
@mrj This has been fixed in our development process. This will be available in chrome store as we publish our next version along with more changes.

**Comment by sachinjain024** [comment]
This is available in Chrome Store. I forgot to update this ticket. Closing this ticket. Please reopen if you see any issues.
