### ISSUE TITLE
Replace rule does not keep extra headers

### ISSUE THREAD

**Issue by ssedrick** [requestly/requestly-issues#52]
I'm trying to redirect a url from `localhost:4200/ds/` to `localhost:8443/`. The redirect is fine, using a replace rule, but the headers (not modified in requestly at all) are not being passed to the new request.  The headers are authentication headers, so they are vital to the functioning of the API.
Is this something requestly can fix? Or is this a browser/http limitation?

**Comment by sachinjain024** [comment]
@ssedrick I need to know a few more things from you before I can provide more help on this.

Q1. How is authentication header passed to localhost:4200 before you set up the replace rule in Requestly? 
Q2. Is authentication done manually or headers are passed via code?

**Comment by ssedrick** [comment]
@sachinjain024 I think I figured out the root issue. CORS wasn't handled correctly in my server code running on `:8443`. Once I set up CORS, it started working. Thanks!
