### ISSUE TITLE
not work firefix 52.0 x64 

### ISSUE THREAD

**Issue by DandyClubs** [requestly/requestly-issues#6]
yesterday i update firefox 52.0

requestly is not work.

**Comment by sachinjain024** [comment]
Thanks @DandyClubs for logging this one. I will take a look at this today.

**Comment by sachinjain024** [comment]
Thanks @DandyClubs for logging this issue. I debugged the issue and asked a question on Mozilla discourse about the out of order of execution of content scripts -  https://discourse.mozilla-community.org/t/order-of-execution-of-content-scripts-in-mozilla-web-extension/14365

**Comment by sachinjain024** [comment]
There is a discussion on Mozilla discussion community, this might be a Firefox bug. I'll try to handle this on myself though.

**Comment by sachinjain024** [comment]
I have fixed this in v4.2.10. Please update your extension using these steps:
1. Go to about:addons
2. Check for updates

Closing this. Let me know if you face any issues. Thanks for reporting.
